### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by juanibiapina** [willbryant/parallel_rspec#5]
I added this to a project and it complained about not having `rake`. After adding `rake` to the Gemfile just to fulfill this requirement, it complained about not having `rails`.

**Comment by willbryant** [comment]
Hmm yeah. In theory this gem would work without Rails, but I haven't tested it.  What are you using?

**Comment by juanibiapina** [comment]
Nothing, just rspec and faraday, calling a few endpoints and checking responses.

**Comment by willbryant** [comment]
OK.  I guess I need to figure out whether Rails is also present and not load `railtie` if not.

I think this is the offending line, in lib/parallel_rspec.rb:

```
require "parallel_rspec/railtie"
```

I do need it to *try* and load Rails, because it needs to add a Railtie, but I guess I can just wrap the whole thing in a LoadError rescue.

If you comment out that line, does the rest of it work?

**Comment by juanibiapina** [comment]
I don't have a need (or time) to pursue this anymore, sorry :(. Feel free to close it if you want.

**Comment by willbryant** [comment]
OK cool, I committed the rescue and some other tweaks for non-Rails apps, so hopefully it's working now anyway.
